options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/medi-go-eb65e/fastapi-backend', '.']

images:
  - 'gcr.io/medi-go-eb65e/fastapi-backend'
