options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/medi-go-eb65e/fastapi-backend', '.']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - fastapi-backend
      - --image=gcr.io/medi-go-eb65e/fastapi-backend
      - --region=us-central1       # 🔁 change this to your preferred region
      - --platform=managed
      - --allow-unauthenticated

images:
  - 'gcr.io/$PROJECT_ID/fastapi-backend'
