steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/medi-go-eb65e/fastapi-backend', '.']

  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/medi-go-eb65e/fastapi-backend']

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - fastapi-backend
      - --image=gcr.io/medi-go-eb65e/fastapi-backend
      - --platform=managed
      - --region=us-central1
      - --allow-unauthenticated

# Optional: Specify images this build produces
images:
  - gcr.io/medi-go-eb65e/fastapi-backend
