steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/medi-go-eb65e/fastapi-backend', '.']

  # Step 2: Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/medi-go-eb65e/fastapi-backend']

images:
  - 'gcr.io/medi-go-eb65e/fastapi-backend'

